Siganushka\ProductBundle\Entity\ProductVariant:
    attributes:
        id:
            groups: ['product_variant:collection', 'product:item', 'product:collection']
        code:
            groups: ['product_variant:collection', 'product:item', 'product:collection']
        name:
            groups: ['product_variant:collection', 'product:item', 'product:collection']
        price:
            groups: ['product_variant:collection', 'product:item', 'product:collection']
        stock:
            groups: ['product_variant:collection', 'product:item', 'product:collection']
        img:
            groups: ['product_variant:collection', 'product:item', 'product:collection']
        outOfStock:
            groups: ['product_variant:collection', 'product:item', 'product:collection']
        enabled:
            groups: ['product_variant:collection', 'product:item', 'product:collection']
        createdAt:
            groups: ['product_variant:collection', 'product:item', 'product:collection']
        updatedAt:
            groups: ['product_variant:collection', 'product:item', 'product:collection']
