Siganushka\ProductBundle\Entity\ProductVariant:
    properties:
        price:
            - NotBlank: { groups: [PriceRequired] }
            - GreaterThanOrEqual: 0
        stock:
            - GreaterThanOrEqual: 0
