Siganushka\ProductBundle\Entity\Product:
    properties:
        img:
            - NotBlank: ~
        name:
            - NotBlank: ~
        options:
            - Valid: ~
            - Count: { min: 1, max: 3, groups: [OptionsRequired] }
            - Unique: { normalizer: 'Siganushka\ProductBundle\Form\ProductOptionType::normalize', groups: [OptionsRequired] }
